# This is a basic workflow to help you get started with Actions

name: generate markdown

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Enter branch to use YAML files from'
        required: true
        type: string
      model_folder:
        description: 'Enter folder to use YAML files from'
        required: true
        type: string
jobs:
  call-workflow-1-in-local-repo:
    uses: BackNot/core/.github/workflows/reusable.yml@d8ddbd2e447ee24bbcd4a15472dd57c60834285b
    with:
      language: es
      branch: ${{inputs.branch}}
      model_folder: ${{inputs.model_folder}}
